export const TeamData = [
    { korean_name: '기아 타이거즈', english_name: 'kia' },
    { korean_name: '두산 베어스', english_name: 'doosan' },
    { korean_name: '롯데 자이언츠', english_name: 'lotte' },
    { korean_name: '삼성 라이온즈', english_name: 'samsung' },
    { korean_name: '키움 히어로즈', english_name: 'kiwoom' },
    { korean_name: '한화 이글스', english_name: 'hanwha' },
    { korean_name: 'KT 위즈', english_name: 'kt' },
    { korean_name: 'LG 트윈스', english_name: 'lg' },
    { korean_name: 'NC 다이노스', english_name: 'nc' },
    { korean_name: 'SSG 랜더스', english_name: 'ssg' }
];

export const ScheduleData = [
    { date: null, korean_name: null, english_name: null },
    { date: null, korean_name: null, english_name: null },
    { date: null, korean_name: null, english_name: null },
    { date: null, korean_name: null, english_name: null },
    { date: null, korean_name: null, english_name: null },
    { date: null, korean_name: null, english_name: null },
    { date: 1, korean_name: '두산 베어스', english_name: 'doosan' },
    { date: 2, korean_name: null, english_name: null },
    { date: 3, korean_name: '삼성 라이온즈', english_name: 'samsung' },
    { date: 4, korean_name: 'KT 위즈', english_name: 'kt' },
    { date: 5, korean_name: 'KT 위즈', english_name: 'kt' },
    { date: 6, korean_name: '삼성 라이온즈', english_name: 'samsung' },
    { date: 7, korean_name: 'SSG 랜더스', english_name: 'ssg' },
    { date: 8, korean_name: 'SSG 랜더스', english_name: 'ssg' },
    { date: 9, korean_name: null, english_name: null },
    { date: 10, korean_name: 'LG 트윈스', english_name: 'lg' },
    { date: 11, korean_name: 'SSG 랜더스', english_name: 'ssg' },
    { date: 12, korean_name: '기아 타이거즈', english_name: 'kia' },
    { date: 13, korean_name: '한화 이글스', english_name: 'hanwha' },
    { date: 14, korean_name: '한화 이글스', english_name: 'hanwha' },
    { date: 15, korean_name: '한화 이글스', english_name: 'hanwha' },
    { date: 16, korean_name: null, english_name: null },
    { date: 17, korean_name: 'LG 트윈스', english_name: 'lg' },
    { date: 18, korean_name: 'LG 트윈스', english_name: 'lg' },
    { date: 19, korean_name: 'LG 트윈스', english_name: 'lg' },
    { date: 20, korean_name: null, english_name: null },
    { date: 21, korean_name: null, english_name: null },
    { date: 22, korean_name: '한화 이글스', english_name: 'hanwha' },
    { date: 23, korean_name: '한화 이글스', english_name: 'hanwha' },
    { date: 24, korean_name: 'KT 위즈', english_name: 'kt' },
    { date: 25, korean_name: '기아 타이거즈', english_name: 'kia' },
    { date: 26, korean_name: '두산 베어스', english_name: 'doosan' },
    { date: 27, korean_name: 'NC 다이노스', english_name: 'nc' },
    { date: 28, korean_name: '기아 타이거즈', english_name: 'kia' },
    { date: 29, korean_name: null, english_name: null },
    { date: 30, korean_name: null, english_name: null },
    { date: null, korean_name: null, english_name: null },
    { date: null, korean_name: null, english_name: null },
    { date: null, korean_name: null, english_name: null },
    { date: null, korean_name: null, english_name: null },
    { date: null, korean_name: null, english_name: null },
    { date: null, korean_name: null, english_name: null }
];

export const RecordData = [
    { korean_name: '두산 베어스', english_name: 'doosan', win: 8, draw: 1, lose: 7 },
    { korean_name: '한화 이글스', english_name: 'hanwha', win: 9, draw: 0, lose: 7 },
    { korean_name: '기아 타이거즈', english_name: 'kia', win: 8, draw: 1, lose: 7 },
    { korean_name: '키움 히어로즈', english_name: 'kiwoom', win: 8, draw: 0, lose: 8 },
    { korean_name: 'KT 위즈', english_name: 'kt', win: 7, draw: 1, lose: 8 },
    { korean_name: 'LG 트윈스', english_name: 'lg', win: 5, draw: 0, lose: 11 },
    { korean_name: 'NC 다이노스', english_name: 'nc', win: 9, draw: 0, lose: 7 },
    { korean_name: '삼성 라이온즈', english_name: 'samsung', win: 6, draw: 0, lose: 10 },
    { korean_name: 'SSG 랜더스', english_name: 'ssg', win: 6, draw: 1, lose: 9 }
];
